### PR TITLE
Bug Sweep - More translations, sorting, and tag editing

### LINKED ISSUE #124: Hexmap name popup is not properly centered in french
The popup appears on the hex northwest of the one selected. This does not happen when the interface is in english.

hexmap popup nw

### LINKED ISSUE #125: Some expressions are not properly translated in french on the interface
The issue is not with the translation itself, because it's all right in some places. I'll list them here. 

- In the right panel, when you select a planet, the expression "Planet tags" read "Planète Marqueurs" in french. It should read "Marqueurs de planètes". 
- In the overview, the title of the list still reads "Entities", It should read "Entités". 

If I see some others, I'll add them. Thanks!

### LINKED ISSUE #126: Ordering of the world tags in the dropdown menu in french
The dropdown menu for world tags when you edit a planet is (probably) ordered in the english alphabetical order. It would be useful to order it in alphabetical order in french, too.

### LINKED ISSUE #127: World Tag Add/Remove is Buggy
You can't remove all the tags. When you try and then you add more it replaces the first one.

### PR DESCRIPTION
**Pull request by mpigsley**
## Description

See resolved issues or changelog for all the specifics.

Resolves #127  (Fix the adding/removing of world tags)
Resolves #126 (Sort world tags for all languages)
Resolves #125 (Translate some missing strings)
Resolves #124 (Center hex tooltips for all languages)

### CODE REVIEW

**Comment by JordanRR** [comment]
#125 the right menu now read "Marqueurs de {singular noun}". 
marqueurs de singular noun

**Comment by JordanRR** [comment]
#127 The "cancel" button saves changes when you add/remove planet tags.

**Comment by mpigsley** [comment]
@JordanRR I'm pushing out a fix now.

**Comment by JordanRR** [comment]
Looks like it worked! Thanks!

**Pull request merged**
